{{
    config(
        materialized='view',
    )
}}

with VW_GL_CHARGES as 
(
select 
    STR_PRIVATE_FLAG,
	TSP_TIMESTAMP,
	MNY_GL_CHARGES_TAXES,
	DTM_LAST_MOD_DATE,
	MNY_GL_CHARGES_TOTAL,
	STR_CODE,
	MNY_EXCHANGE_RATE,
	STR_GL_CHARGES_NOTES,
	STR_VISIBLE_FLAG,
	BIT_FULLY_PAID,
	MNY_GL_CHARGES_AMOUNT,
	MNY_GL_CHARGES_DISCOUNT,
	MNY_GL_CURRENCY_CHARGES_TAXES,
	STR_SUB_CODE,
	STR_REFUNDABLE_CHARGE,
	DTM_CREATION_DATE,
	STR_GL_CHARGES_DESC,
	MNY_GL_CURRENCY_CHARGES_DISCOUNT,
	DTM_GL_CHARGES_DATE,
	STR_DOC_TYPE_FLAG,
	MNY_GL_CURRENCY_CHARGES_TOTAL,
	MNY_GL_CURRENCY_CHARGES_AMOUNT,
	_FIVETRAN_DELETED,
	_FIVETRAN_SYNCED,
	LNG_CREATION_USER_ID_NMBR,
	LNG_LAST_MOD_USER_ID_NMBR,
	LNG_RESERVATION_NMBR,
	LNG_RES_LEGS_ID_NMBR,
	LNG_GL_SURCHARGE_ID_NMBR,
	LNG_GL_CHARGES_ID_NMBR,
	LNG_TAX_CONFIGURATION_ID_NMBR,
	LNG_GL_DISCOUNTS_ID_NMBR,
	LNG_GL_CHARGE_TYPE_ID_NMBR,
	LNG_CURRENCY_ID_NMBR,
	TGT_CREATE_DT,
	TGT_UPDATE_DT,
	EFFECTIVE_START_DATE,
	EFFECTIVE_END_DATE,
	ACTIVE_FLAG	
FROM
    {{ ref('stg_gl_charges') }}	
WHERE 
    ACTIVE_FLAG = 'Y'     
)
SELECT * from VW_GL_CHARGES