{{
    config(
        materialized='view',
    )
}}

with VW_RES_LEGS as 
(
select
	LNG_RES_LEGS_ID_NMBR,
	STR_LEG_STATUS,
	TSP_TIMESTAMP,
	STR_REALIZED_REVENUE,
	STR_PRIVATE_FLAG,
	DTM_CREATION_DATE,
	LNG_CREATION_USER_ID_NMBR,
	LNG_RESERVATION_NMBR,
	LNG_LEG_NMBR,
	LNG_PROMO_CODE_DEFINITION_ID_NMBR,
	LNG_ARR_AIRPORT_ID_NMBR,
	STR_EMAIL_ALERT,
	DTM_DATE,
	LNG_RES_PAX_GROUP_ID_NMBR,
	STR_SHUTTLE_BUS_FLAG,
	LNG_LAST_MOD_USER_ID_NMBR,
	LNG_PROMO_CODE_SUFFIX_ID_NMBR,
	STR_COMMENTS,
	LNG_DEP_AIRPORT_ID_NMBR,
	STR_TICKET_NMBR,
	MNY_FARE_COST,
	DTM_LAST_MOD_DATE,
	_FIVETRAN_DELETED,
	_FIVETRAN_SYNCED,
	TGT_CREATE_DT,
	TGT_UPDATE_DT,
	EFFECTIVE_START_DATE,
	EFFECTIVE_END_DATE,
	ACTIVE_FLAG
 FROM  	dev.stage.sTG_Res_Legs	WHERE ACTIVE_FLAG = 'Y' 
)
select * from vw_res_legs