{% macro stage_metadata_columns() -%}

        CURRENT_TIMESTAMP() AS TGT_CREATE_DT,
        CURRENT_TIMESTAMP() AS TGT_UPDATE_DT,
        CURRENT_TIMESTAMP() AS EFFECTIVE_START_DATE,
        IFF(_FIVETRAN_DELETED='TRUE',CURRENT_TIMESTAMP(),CAST('9999-12-31 23:59:59' AS TIMESTAMP)) AS EFFECTIVE_END_DATE,
        IFF(_FIVETRAN_DELETED='TRUE','N','Y') AS ACTIVE_FLAG,

{%- endmacro %}